# Generated by Django 2.2 on 2020-06-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_attraction', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='final_time',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='track',
        ),
        migrations.AddField(
            model_name='plan',
            name='route',
            field=models.ManyToManyField(to='ordered_attraction.OrderedAttraction'),
        ),
        migrations.AddField(
            model_name='plan',
            name='route_length',
            field=models.FloatField(default=0.0),
        ),
    ]
