# Generated by Django 2.2 on 2020-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200603_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='route',
            field=models.ManyToManyField(blank=True, null=True, to='ordered_attraction.OrderedAttraction'),
        ),
    ]
