# Generated by Django 2.2 on 2020-05-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='city.City'),
        ),
    ]
