# Generated by Django 2.2 on 2020-05-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_auto_20200522_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
