# Generated by Django 2.2 on 2020-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0006_auto_20200529_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='attraction/images'),
        ),
    ]
