# Generated by Django 2.2 on 2020-06-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attraction', '0010_auto_20200531_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('travel_time', models.PositiveIntegerField(blank=True, null=True)),
                ('travle_length', models.FloatField(blank=True, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attraction.Attraction')),
            ],
        ),
    ]
